# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=20)),
                ('doctor_name', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('service_charges', models.CharField(max_length=20)),
                ('item_details', models.TextField()),
                ('patient_details', models.TextField()),
                ('for_date', models.CharField(max_length=20)),
                ('entry_created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
